/**
 * Loosechain Layer 1: Delta Engine Core - Types
 * These types constitute the "Protocol Law" and must remain stable.
 */

/** Quantity/dimension class — not NetworkReceipt.kind or MeasurementSource.kind. */
export type QuantityKind =
  | 'money'
  | 'percentage'
  | 'count'
  | 'date'
  | 'trend'
  | 'quantity';

/** Whether a unit string was host-declared or text-inferred (never authoritative for comparability). */
export type UnitSource = 'declared' | 'inferred' | 'none';

export interface ObservationCodeLists {
  ucum?: string;
  clObsStatus?: string;
  prov?: string;
  stake?: string;
}

export interface MetricPoint {
  key: string;
  value: number;
  unit?: string;
  /** Authority of `unit`. Comparability accepts only `declared`. */
  unitSource?: UnitSource;
  quantityKind?: QuantityKind;
  /** ISO — measurement/observation time. Drives freshness when declared. */
  measuredAt?: string;
  /** ISO — period/instant the value applies to. */
  appliesTo?: string;
  /** SDMX CL_OBS_STATUS code (A/E/P/F/I/U/V). */
  obsStatus?: string;
  /** UVRN stake code — observational, not motive. */
  stake?: string;
  codeLists?: ObservationCodeLists;
  /**
   * Optional ISO timestamp. MUST NOT be filled from document publish time
   * (`publishedAt`). When used, prefer host-declared `measuredAt`.
   */
  ts?: string;
}

/** First-class refusal — no delta enters scoring for the refused pair/key. */
export interface ComparabilityRefusal {
  type: 'comparability-refusal';
  reason: 'dimension-mismatch' | 'missing-unit' | 'inferred-unit-ineligible';
  left?: { sourceId?: string; quantityKind?: QuantityKind; unit?: string };
  right?: { sourceId?: string; quantityKind?: QuantityKind; unit?: string };
}

export interface DataSpec {
  id: string; // Unique identifier
  label: string; // Human readable label
  sourceKind: 'report' | 'metric' | 'chart' | 'meta';
  originDocIds: string[];
  metrics: MetricPoint[];
}

export interface DeltaBundle {
  bundleId: string;
  claim: string;
  dataSpecs: DataSpec[];
  thresholdPct: number; // 0.0 to 1.0
  maxRounds?: number; // Defaults to 5
  /**
   * Optional absolute near-zero tolerance. When set, pairs with
   * |a − b| ≤ absoluteEpsilon are treated as delta 0.
   * Unset means unset — no default; frozen engine behavior unchanged.
   */
  absoluteEpsilon?: number;
}

export interface DeltaRound {
  round: number;
  deltasByMetric: Record<string, number>;
  withinThreshold: boolean;
  witnessRequired: boolean;
  notes?: string[]; // Deterministic strings only
}

export type Outcome = 'consensus' | 'indeterminate';

export interface DeltaReceipt {
  bundleId: string;
  deltaFinal: number; // Max delta across metrics in last round
  sources: string[]; // DataSpec labels, deterministically ordered
  rounds: DeltaRound[];
  suggestedFixes: []; // Always empty in Core (Layer 2 concern)
  outcome: Outcome;
  ts?: string; // ISO timestamp (Input only, not generated by Core)
  hash: string; // SHA-256 of canonical payload
}

export interface ValidationResult {
  valid: boolean;
  error?: string;
}

export interface VerifyResult {
  verified: boolean;
  recomputedHash?: string;
  error?: string;
}

export interface EngineOpts {
  // Option to inject external timestamp if needed for envelope
  timestamp?: string;
}

/**
 * Canonical V-Score component weights. The V-Score formula lives only in
 * `@uvrn/core` (house rule #1); `@uvrn/score` re-exports these as `WEIGHTS` and
 * decomposes them into a ScoreBreakdown. Single source of truth — do not redefine.
 */
export const VSCORE_WEIGHTS = {
  completeness: 0.35,
  parity: 0.35,
  freshness: 0.3,
} as const;

export * from './measurement';
export * from './master-receipt';
