/**
 * UVRN Layer 1: Delta Engine Core - Types
 * These types constitute the "Protocol Law" and must remain stable.
 */

export interface MetricPoint {
  key: string;
  value: number;
  unit?: string;
  ts?: string; // ISO string, optional
}

export interface DataSpec {
  id: string; // Unique identifier
  label: string; // Human readable label
  sourceKind: 'report' | 'metric' | 'chart' | 'meta';
  originDocIds: string[];
  metrics: MetricPoint[];
}

export interface DeltaBundle {
  bundleId: string;
  claim: string;
  dataSpecs: DataSpec[];
  thresholdPct: number; // 0.0 to 1.0
  maxRounds?: number; // Defaults to 5
}

export interface DeltaRound {
  round: number;
  deltasByMetric: Record<string, number>;
  withinThreshold: boolean;
  witnessRequired: boolean;
  notes?: string[]; // Deterministic strings only
}

export type Outcome = 'consensus' | 'indeterminate';

export interface DeltaReceipt {
  bundleId: string;
  deltaFinal: number; // Max delta across metrics in last round
  sources: string[]; // DataSpec labels, deterministically ordered
  rounds: DeltaRound[];
  suggestedFixes: []; // Always empty in Core (Layer 2 concern)
  outcome: Outcome;
  ts?: string; // ISO timestamp (Input only, not generated by Core)
  hash: string; // SHA-256 of canonical payload
}

export interface ValidationResult {
  valid: boolean;
  error?: string;
}

export interface VerifyResult {
  verified: boolean;
  recomputedHash?: string;
  error?: string;
}

export interface EngineOpts {
  // Option to inject external timestamp if needed for envelope
  timestamp?: string;
}
