import type { LatticeTemplate } from '../types';

const BASE_SIGNAL_CATEGORIES = [
  'evidence_strength',
  'domain_fit',
  'implementation_readiness',
];

export const BUILT_IN_TEMPLATES: LatticeTemplate[] = [
  {
    id: 'builder-radar',
    name: 'Builder Radar',
    domains: ['economic', 'technical', 'cultural', 'legal'],
    signalCategories: BASE_SIGNAL_CATEGORIES,
    normalization: 'domain-average',
    outputFrame: 'builder-readiness',
    depth: 'standard',
    tier: 'base',
    explanation: 'Scaffolds a cross-domain readiness read for builder-facing opportunities.',
  },
  {
    id: 'content-opportunity',
    name: 'Content Opportunity',
    domains: ['cultural', 'economic', 'technical'],
    signalCategories: BASE_SIGNAL_CATEGORIES,
    normalization: 'domain-average',
    outputFrame: 'content-opportunity',
    depth: 'standard',
    tier: 'base',
    explanation: 'Scaffolds content opportunity evidence across audience, market, and feasibility signals.',
  },
  {
    id: 'market-narrative',
    name: 'Market Narrative',
    domains: ['financial', 'economic', 'legal', 'cultural'],
    signalCategories: BASE_SIGNAL_CATEGORIES,
    normalization: 'domain-average',
    outputFrame: 'market-narrative',
    depth: 'deep',
    tier: 'pro',
    explanation: 'Scaffolds narrative-market agreement across financial, macro, legal, and cultural domains.',
  },
  {
    id: 'seo-topic-intelligence',
    name: 'SEO Topic Intelligence',
    domains: ['seo', 'cultural', 'economic'],
    signalCategories: BASE_SIGNAL_CATEGORIES,
    normalization: 'domain-average',
    outputFrame: 'seo-topic-intelligence',
    depth: 'standard',
    tier: 'pro',
    explanation: 'Scaffolds topic intelligence across search, audience, and market signals.',
  },
  {
    id: 'campaign-intelligence',
    name: 'Campaign Intelligence',
    domains: ['economic', 'technical', 'cultural'],
    signalCategories: BASE_SIGNAL_CATEGORIES,
    normalization: 'domain-average',
    outputFrame: 'campaign-intelligence',
    depth: 'standard',
    tier: 'pro',
    explanation: 'Scaffolds campaign planning evidence across demand, implementation, and audience domains.',
  },
  {
    id: 'full-lattice',
    name: 'Full Lattice',
    domains: ['cultural', 'economic', 'technical', 'legal', 'financial', 'scientific', 'seo'],
    signalCategories: BASE_SIGNAL_CATEGORIES,
    normalization: 'domain-average',
    outputFrame: 'full-lattice',
    depth: 'deep',
    tier: 'studio',
    explanation: 'Scaffolds full cross-domain evidence decomposition for studio-tier research questions.',
  },
];
